spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      max-file-size: 4MB
server:
  servlet:
    encoding:
      force-response: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
aws-s3:
  access-key: ${AWS_S3_ACCESS_KEY}
  secret-access-key: ${AWS_S3_SECRET_ACCESS_KEY}
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 60
  refresh-token-expiration-days: 7