spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      max-file-size: 4MB
server:
  servlet:
    encoding:
      force-response: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    auth: true
    starttls:
      enable: true
  subject:
    member:
      reset-password: 임시비밀번호 안내 관련 이메일 입니다.
  template:
    name:
      member:
        reset: email-password-reset
aws-s3:
  access-key: ${AWS_S3_ACCESS_KEY}
  secret-access-key: ${AWS_S3_SECRET_ACCESS_KEY}
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 60
  refresh-token-expiration-days: 7
decorator:
  datasource:
     p6spy:
      enable-logging: true