name: PR Test

on:
  pull_request:
    branches: [ be-dev ] # master branch에 PR을 보낼 때 실행

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Set yml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ./server/src/main/resources/application*.yml
        env:
          aws-s3.access-key: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-s3.secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          jwt.key: ${{secrets.JWT_SECRET_KEY}}
          mail.smtp.username: ${{secrets.EMAIL_USERNAME}}
          mail.smtp.password: ${{secrets.EMAIL_PASSWORD}}
          spring.datasource.url: ${{ENDPOINT}}, ${{PORT_NUMBER}}, ${{DATABASE}}
          spring.datasource.username: ${{MY_SQL_ID}}
          spring.datasource.password: ${{PASSWORD}}
      # Gradle wrapper 파일 실행 권한주기
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle test를 실행한다
      - name: Test with Gradle
        run: ./gradlew --info test